---
title: Installeer Sonic Pi
hero_image: images/banner.png
description: Hoe Sonic Pi te installeren
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Inleiding

