title: sonic-pi-install
hero_image: images/banner.png
description: sonic-pi-install description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-02"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
