---
title: Instalar Sonic Pi
hero_image: images / banner.png
description: Cómo instalar Sonic Pi
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Introducción

