---
title: Sonic Pi installieren
hero_image: images/banner.png
description: Wie man Sonic Pi installiert
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Einleitung

