---
title: Instalează Sonic Pi
hero_image: images/banner.png
description: Cum să instalezi Sonic Pi
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Introducere

