---
title: Instal路laci贸 de Sonic Pi
hero_image: images/banner.png
description: Com instal路lar Sonic Pi
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Introducci贸

