---
title: Εγκατάσταση Sonic Pi
hero_image: images/banner.png
description: Πώς να εγκαταστήσεις το Sonic Pi
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - title: Εισαγωγή

