---
title: Installer Sonic Pi
hero_image: images/banner.png
description: Comment installer Sonic Pi
version: 4
listed: false
copyedit: true
last_tested: "2019-05-02"
steps:
  - 
    title: Introduction

